<?php $arrQuery = $this->request->getQuery();
unset($arrQuery['_url'], $arrQuery['page']);
?>
<div class="bread-block-wrap">
    <div class="breadcrumb-keyword-bg" data-spm="2">
        <div class="breadcrumb-keyword list-responsive-container">
            <div data-widget-cid="widget-11" id="aliGlobalCrumb" class="ui-breadcrumb">
                <a href="<?php echo $this->url->get() ?>" rel="nofollow" title="Home">Home</a>
                <span class="divider">&gt;</span>
                <h1>
                    <?php if ($category->ct_parent_id != 0 || !empty($category->ct_parent_id)) {
                        $categoryParent = $category->getCategoryParent(); ?>
                        <a href="<?php echo $this->url->get("category-product/show/") . $categoryParent->ct_seo_link ?>"
                           title="<?php echo $category->ct_name ?>"><?php echo $categoryParent->ct_name ?></a>

                        <span class="divider">&gt;</span> <span> <?php echo $category->ct_name ?></span>
                    <?php } else { ?>
                        <span> <?php echo $category->ct_name ?></span>
                    <?php } ?>
                </h1>
            </div>
        </div>
    </div>
</div>
<div id="page" class="categories-collapse autosize_wrap en-us">
    <div class="grid-c2-s5 util-clearfix">
        <div class="col-main">
            <div id="main-wrap" class="main-wrap gallery-mode">
                <?php if ($category->ct_parent_id == 0 || empty($category->ct_parent_id)) {
                    $categoryChild = $category->getCategoryChild(); ?>
                    <div id="hot-tag" class="hot-tag util-clearfix">
                        <span class="hot-tag-title">Hot Now</span>
                                <span class="hot-tag-list">
                                    <?php if ($categoryChild) {
                                        foreach ($categoryChild as $cateCh) { ?>
                                            <a href="<?php echo $this->url->get("category-product/show/") . $cateCh->ct_seo_link ?>"
                                               class="tag-items "
                                               title="<?php echo $cateCh->ct_name ?>"><span><?php echo $cateCh->ct_name ?></span></a>
                                        <?php }
                                    } ?>
                                </span>
                        <i style="display: inline;" class="hot-tag-view-more"></i>
                    </div>
                <?php } ?>

                <form id="narrow-form" method="get"
                      action="<?php echo $this->url->get("category-product/show/") . $category->ct_seo_link ?>">
                    <div class="narrow-down-area" id="narrow-down-area">
                        <div id="filter" class="util-clearfix">
                            <div style="position: static;" class="filter-price-c">
                                            <span id="filter-price" class="price_histogram">
                                                <span class="ui-label">Price:</span>
                                                <input class="ui-textfield ui-textfield-system" name="minPrice"
                                                       id="filter-price-from" autocomplete="off"
                                                       value="<?php echo isset($arrQuery['minPrice']) ? $arrQuery['minPrice'] : ''; ?>"
                                                       required number="true" placeholder="min"> <span>-</span>
                                                <input class="ui-textfield ui-textfield-system"
                                                       value="<?php echo isset($arrQuery['maxPrice']) ? $arrQuery['maxPrice'] : ''; ?>"
                                                       name="maxPrice" id="filter-price-to" required number="true"
                                                       placeholder="max">
                                            </span>
                                <input type="submit" class="ui-button narrow-go" id="filter-submit"
                                       style="display:none">
                            </div>


                            <div id="filter-options" class="n-check-filter option-more">
                                <a id="linkOnSale" onclick="filterCategoryProduct('promotion', '1',$(this));"
                                   href="javascript:;"
                                   class="sale-items filter-item <?php echo isset($arrQuery['promotion']) ? ' selected ' : '' ?>">
                                    <i class="check-icon"></i>
                                    <span class="a-sale-items"> Sale Items </span>
                                </a>
                                <div style="margin-top: 7px;" class="n-sort-filter">
                                    <span class="sort-by-text">Giá:</span>
                                    <div class="n-sort-lists">
                                        <div class="narrow-down-bg first">
                                            <a rel="nofollow" data-filter-type="bestMatch" href="javascript:;"
                                               onclick="filterCategoryProduct('price', 'asc',$(this));">
                                                <span id="link-best-match"
                                                      class="<?php echo isset($arrQuery['price']) && $arrQuery['price'] == 'asc' ? ' best-match-on ' : '' ?>">Thấp Tới Cao</span>
                                            </a>
                                        </div>

                                        <div class="narrow-down-bg">
                                            <a rel="nofollow" data-filter-type="orders" href="javascript:;"
                                               onclick="filterCategoryProduct('price', 'desc',$(this));">
                                                <span
                                                    class="<?php echo isset($arrQuery['price']) && $arrQuery['price'] == 'desc' ? ' best-match-on ' : '' ?>"
                                                    id="number_of_orders_1">Cao Tới Thấp</span>
                                            </a>
                                        </div>

                                    </div>


                                </div>
                            </div>
                        </div>
                        <div
                            style="width: 350px; z-index: 10; display: none; position: absolute; left: 290.7px; top: 10px;"
                            data-widget-cid="widget-21" class="ui-balloon ui-balloon-lt">
                            <div class="ui-notice ui-notice-normal dependency">
                                <div class="ui-notice-content">
                                    <a href="javascript:;" class="ui-close" data-role="close">close</a>
                                    <h4 class="ui-notice-header" data-role="title">New Feature!</h4>
                                    <div class="ui-notice-body" data-role="content">To make it easier to find your
                                        perfect product, you can now filter search results by price ranges.
                                    </div>
                                </div>
                            </div>

                            <a class="ui-balloon-arrow" data-role="arrow"></a>
                        </div>
                    </div>
                </form>


                <div id="gallery-item">
                    <div id="list-items" class="clearfix temp-height lazy-load" data-spm="3">

                        <ul class="util-clearfix son-list">

                            <?php if ($products) {
                                foreach ($products->items as $product) { ?>
                                    <li class="list-item list-item-first ">
                                        <div class="item">
                                            <div class="img img-border">
                                                <div class="pic">
                                                    <a class="picRind "
                                                       href="<?php echo $this->url->get("product/show/") . $product->pr_seo_link ?>">
                                                        <img class="picCore pic-Core-v"
                                                             src="<?php echo $product->showImage() ?>"
                                                             alt="<?php echo $product->pr_name ?>">
                                                    </a>
                                                </div>
                                            </div>


                                            <div class="info">
                                                <h3>
                                                    <a class="product "
                                                       href="<?php echo $this->url->get("product/show/") . $product->pr_seo_link ?>"
                                                       title="<?php echo $product->pr_name ?>"><?php echo $product->pr_name ?>
                                                    </a>
                                                </h3>
                                                <?php if ($product->showPricePromotion()) { ?>
                                                    <span class="price price-m">
                                                        <span class="value"
                                                              itemprop="price"><?php echo $product->showPricePromotion() ?></span>
                                                    </span>
                                                    <div>
                                                        <del
                                                            class="original-price"> <?php echo $product->getMinimumPrice() ?></del>
                                                    </div>
                                                <?php } else { ?>
                                                    <span class="price price-m"><span class="value"
                                                                                      itemprop="price"><?php echo $product->getMinimumPrice() ?></span></span>
                                                <?php } ?>
                                                <div class="rate-history">
                                                        <span style="float:right" rel="nofollow" class="order-num">
                                                            <a class="order-num-a " href="javascript:;" rel="nofollow">
                                                                <em title="Total Orders"> Đã bán (<?php echo $product->countOrder() ?>
                                                                    )</em>
                                                            </a>
                                                        </span>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                <?php }
                            } ?>
                        </ul>
                    </div>


                </div>


                <div data-widget-cid="widget-10" id="pagination-bottom"
                     class="ui-pagination ui-pagination-front ui-pagination-body util-clearfix" data-spm-protocol="i">
                    <div class="ui-pagination-navi util-left">
                        <a href="<?php echo $this->url->get() . "category-product/show/" . $category->ct_seo_link . "?page=" . $products->before . "&" . http_build_query($arrQuery) ?>"
                           class="ui-pagination-prev ui-pagination-disabled">Previous</a>
                        <?php for ($i = 1; $i <= $products->total_pages; $i++) { ?>
                            <a <?php if ($products->current == $i) {
                                echo ' class="ui-pagination-active" ';
                            } ?>
                                href="<?php echo $this->url->get() . "category-product/show/" . $category->ct_seo_link . "?page=" . $i . "&" . http_build_query($arrQuery) ?>">
                                <?php echo $i; ?>
                            </a>
                        <?php } ?>
                        <a href="<?php echo $this->url->get() . "category-product/show/" . $category->ct_seo_link . "?page=" . $products->next . "&" . http_build_query($arrQuery) ?>"
                           class="page-next ui-pagination-next">Next</a>
                    </div>
                </div>

                <div class="p4pExpress" id="p4pHotProducts-old" data-spm="6"><h4>Today Sale</h4>
                    <div id="relatied-product-slide" class="relatied-product-slide">
                        <div class="relatied-products-container">
                            <ul id="p4p-ul-content" class="p4p-bottom-content clearfix">
                                <?php if ($productSaleRandom) {
                                    foreach ($productSaleRandom as $prsale) { ?>
                                        <li class="p4p-list-item item-index-0" >
                                            <div class="p4p-item-block">
                                                <div class="img-box-wrap">
                                                    <div class="img-box">
                                                        <a rel="nofollow" target="_blank"
                                                           title="<?php echo $prsale->pr_name ?>"
                                                           href="<?php echo $this->url->get("product/show/") . $prsale->pr_seo_link ?>" >
                                                            <img style="visibility: visible;"
                                                                 src="<?php echo $prsale->showImage() ?>"
                                                                 class="auto-set-img0"
                                                                 alt="<?php echo $prsale->pr_name ?>">
                                                        </a>
                                                    </div>
                                                </div>
                                                <p class="p4p-product-title">
                                                    <a rel="nofollow" target="_blank" title="<?php echo $prsale->pr_name ?>"
                                                        href="<?php echo $this->url->get("product/show/") . $prsale->pr_seo_link ?>" >
                                                        <?php echo $prsale->pr_name ?>
                                                    </a>
                                                </p>
                                                <p class="p4p-price-list">
                                                    <?php echo $prsale->showPricePromotion() ?>
                                                </p>
                                                <div class="p4p-oriprice-block">
                                                    <del class="original-price"><?php echo $prsale->getMinimumPrice() ?></del>
                                                </div>
                                            </div>
                                        </li>
                                    <?php }
                                } ?>
                            </ul>
                        </div>
                        <a class="lnk-prev lnk-prev-disabled" id="lnk-prev" title="previous page"></a>
                        <a class="lnk-next" id="lnk-next" title="next page"></a>
                    </div>
                    <div class="p4pClearfix"></div>
                </div>
            </div>
        </div>
        <?php echo $this->partial('category-product/_left_menu') ?>
    </div>
    <script type="text/javascript">
        var seo = '<?php echo $category->ct_seo_link ?>';
        <?php if (!empty($query)) {
            echo "var arrFilter = {" . $query . "};";
        } else {
            echo "var arrFilter = {};";
        } ?>
    </script>