<!--menu Category Product-->
<section class="promotion-block categories">
    <header><a data-spm-anchor-id="0.0.0.0" href="//m.aliexpress.com/categoryList.htm?cateId=0">All Categories</a>
    </header>
    <article>
        <ul class="flex-box">
            <li class="apparel-accessories"><a href="//m.aliexpress.com/categoryList.htm?cateId=10001">Apparel &amp;
                    Accessories</a></li>
            <li class="jewelry"><a href="//m.aliexpress.com/categoryList.htm?cateId=10016">Jewelry</a></li>
            <li class="electronics"><a href="//m.aliexpress.com/categoryList.htm?cateId=10005">Electronics</a></li>
            <li class="beauty-health"><a href="//m.aliexpress.com/categoryList.htm?cateId=10004">Beauty &amp;Health</a>
            </li>
        </ul>
    </article>
</section>
<!--end menu category product-->