<div class="top-container-bg"></div>
<div id="home-firstscreen" class="home-firstscreen container">
    <div class="home-firstscreen-main">
        <!--TMS:1717630-->
        <div class="channel-entrance" data-spm="21">
            <a href="today-deal.html">SuperDeals</a>
            <a href="http://brands.aliexpress.com/">Today Sale</a>
        </div>
        <div class="categories">
            <!--TMS:2128949-->
            <div data-widget-cid="widget-5" class="categories-main new-categories-main categories-main-home"
                 data-role="category-content" data-spm="22">
                <div class="categories-content-title" data-role="exclude">
                    <span>CATEGORIES</span>
                </div>
                <div class="categories-list-box">
                    <?php $array_icon = array('men', 'women', 'shoes', 'shoes', 'jewelry', 'toys', 'garden', 'garden'); ?>
                    <?php if ($manufacturer) {
                        foreach ($manufacturer as $key => $manu) { ?>
                            <dl data-role="first-menu" class="cl-item cl-item-<?php echo $array_icon[$key] ?> "
                                data-spm="101">
                                <dt class="cate-name">
                                    <span><a href="<?php echo $this->url->get("manufacturer/").$manu->ma_id ?>"><?php echo $manu->ma_name ?></a></span>
                                </dt>
                                <?php if (count($manu->CategoryModel) > 0) { ?>
                                    <dd data-role="first-menu-main" class="sub-cate" data-path="c-women-content">
                                        <div class="sub-cate-main">
                                            <?php $categories = $manu->getCategory(); ?>
                                            <?php foreach ($categories as $key => $cate) { ?>
                                                <div class="sub-cate-row">
                                                    <dl data-role="two-menu" class="sub-cate-items">
                                                        <dt>
                                                            <a href="<?php echo $this->url->get("category-product/show/").$cate->ct_seo_link ?>"><?php echo $cate->ct_name ?></a>
                                                        </dt>
                                                        <dd>
                                                            <?php
                                                            $categoryModel = new \Backend\Models\CategoryModel();
                                                            $childCategory = $categoryModel::find(array("ct_parent_id = '{$cate->ct_id}'"));
                                                            if ($childCategory) {
                                                                foreach ($childCategory as $child) {
                                                                    ?>

                                                                    <a href="<?php echo $this->url->get("category-product/show/").$child->ct_seo_link ?>"><?php echo $child->ct_name ?></a>
                                                                <?php }
                                                            } ?>
                                                        </dd>
                                                    </dl>
                                                </div>
                                            <?php } ?>
                                        </div>
                                    </dd>
                                <?php } ?>
                            </dl>
                        <?php }
                    } ?>

                </div>
            </div>
        </div>
        <div class="advertise-main">
            <!--TMS:1909664-->

            <div data-widget-cid="widget-21" class="ui-banner-slider col-md-40 col-lg-40 key-visual-main"
                 id="key-visual-main">
                <div class="ui-banner-slider-wrap">
                    <div class=" ui-banner-slider-container ">
                        <ul class="slides">
                            <?php if ($slider) {
                                foreach ($slider as $sli) { ?>
                                    <li>
                                        <a href="">
                                            <img src="<?php echo $sli->ba_image_link ?>"/>
                                        </a>
                                    </li>
                                <?php }
                            } ?>
                        </ul>
                    </div>
                </div>
            </div><!--TMS:1927272-->
            <?php if ($productSaleRandom) {
                foreach ($productSaleRandom as $key => $prsale) {
                    if ($key == 0) { ?>
                        <div class="top-deal hidden-sm col-md-20 col-lg-20" data-spm="24">
                            <a href="<?php echo $this->url->get("product/show/") . $prsale->pr_seo_link ?>">
                                <div class="top-deal-inner">
                                    <div class="top-deal-product">
                                        <img src="<?php echo $prsale->showImage() ?>" alt="">
                                    </div>
                                    <div class="top-deal-banner">
                                        <div class="top-deal-pic">
                                            <p style="color: #333;font-weight: bold;text-align: center;position: relative;top: 16px;overflow: hidden;text-overflow: ellipsis;"><?php echo $prsale->pr_name ?></p>
                                        </div>
                                        <div class="top-deal-date">
                                            <div class="text">
                                                <p class="up">On sale</p>
                                                <p class="down"><?php echo $prsale->formatDate($prsale->pr_date_sale_from) . " - " . $prsale->formatDate($prsale->pr_date_sale_to) ?></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    <?php }
                }
            } ?>
        </div>
    </div>
</div>
<!--TMS:2022556-->
<style>
    .festival-1111-floor .container-inner {
        border-top: 2px solid #E62E04;
    }
</style>


<?php echo $this->partial('index/category_product_mobile') ?>
<?php echo $this->partial('index/sale_product_mobile') ?>
<?php echo $this->partial('index/list_product_mobile') ?>

<div class="main-deal container">
    <div class="today-deal-panel col-lg-15 col-md-15 today-deal-dos-new">
        <div class="title">
            <h2>
                <a href="today-deal.html"><strong><i>TODAY'S</i> DEALS</strong>
                </a>
            </h2>
            <a style="visibility: visible;" href="" class="view-more hidden-md"
               data-role="viewmore">
                <?php if ($countTodaySale > 0) { ?>
                    <strong><i><?php echo $countTodaySale ?></i></strong> items <?php } ?> </a>
        </div>
        <a href="http://superdeals.aliexpress.com/en">
            <div class="container-main clearfix" data-role="main">
                <div class="end-time">
                    <span style="visibility: visible;">Ends in:<span style="color:#E62E04" id="end-times"></span></span>
                    <script type="text/javascript">
                        $(document).ready(function () {
                            $("#end-times")
                                .countdown("<?php echo date("Y/m/d", strtotime('+2 days', time())); ?>", function (event) {
                                    $(this).text(
                                        event.strftime('%H:%M:%S')
                                    );
                                });
                        });
                    </script>


                </div>
                <?php if ($productSaleRandom) {
                    foreach ($productSaleRandom as $key => $prsale) {
                        if ($key == 1) { ?>
                            <div class="product-pic">
                                <img src="<?php echo $prsale->showImage() ?>">
                            </div>
                            <div class="price-panel">
                                <div class="price">
                                    <span><?php echo $prsale->showPricePromotion() ?></span>
                                    <del><?php echo $prsale->getMinimumPrice() ?></del>
                                </div>
                            </div>
                        <?php }
                    }
                } ?>
            </div>
        </a>

    </div>
    <div class="collections-panel col-lg-45 col-md-45 collections-dos">
        <div class="collections-panel-inner clearfix">
            <div class="title">
                <h2>
                    <a href="collection.html">
                        <span>ALIEXPRESS</span> COLLECTIONS </a>
                </h2>
                <a href="collection.html" class="view-more">View more</a>
            </div>
            <div class="collections col-lg-60" data-role="main">
                <a href="http://activities.aliexpress.com/aetopcollectionsdetails.php?widgetId=561&amp;collection-id=444775&amp;node-id=108229">
                    <div class="collections-left-panel">
                        <img
                            src="<?php echo $this->url->get("public/FrontendCore/") ?>img/TB1P0VgMFXXXXamXpXXzdft9XXX-660-340.jpg"
                            alt="">
                    </div>
                    <div class="top-items">
                        <div class="top-item">
                            <img
                                src="<?php echo $this->url->get("public/FrontendCore/") ?>img/TB1_qRkMFXXXXcJXXXXjrhCTXXX-697-695.jpg"
                                alt="">
                        </div>
                        <div class="other-items">
                            <img src="<?php echo $this->url->get("public/FrontendCore/") ?>img/TB10ilgMFXXXXa0XpXXp.jpg"
                                 alt="">
                            <img src="<?php echo $this->url->get("public/FrontendCore/") ?>img/TB1MkpkMFXXXXbEXXXXp.jpg"
                                 alt="">
                            <img src="<?php echo $this->url->get("public/FrontendCore/") ?>img/TB18Z70MpXXXXbqXVXXp.jpg"
                                 alt="">
                        </div>
                    </div>
                </a>
                <a href="http://activities.aliexpress.com/collectiondetails.php?widgetId=562&amp;collection-id=444788&amp;node-id=108230">
                    <div class="collections-right-panel hidden-sm">
                        <div class="pic-group">
                            <div class="pic rborder bborder">
                                <div class="desc">
                                    <span class="subject">Update Your Tech</span>
                                </div>
                            </div>
                            <div class="pic bborder">
                                <img class="rpic"
                                     src="<?php echo $this->url->get("public/FrontendCore/") ?>img/building-block-USB-Flash-Drive-2-0-cartoon-usb-stick-Toy-blo.jpg"
                                     alt="">
                            </div>
                            <div class="pic rborder">
                                <img class="bpic"
                                     src="<?php echo $this->url->get("public/FrontendCore/") ?>img/Chrismas-Santa-Claus-usb-flash-drive-4g-8g-16g-32g-Creative-.jpg"
                                     alt="">
                            </div>
                            <div class="pic">
                                <img class="bpic rpic"
                                     src="<?php echo $this->url->get("public/FrontendCore/") ?>img/New-Cartoon-Gray-Microphone-Novelty-Model-usb-2-0-memory-fla.jpg"
                                     alt="">
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>

    </div>
</div>  <!--TMS:1811543-->
<!--TMS:2082108 -->
<div data-widget-cid="widget-24" id="ae-recommend-floor-tpp" class="container industry-floor-recommend" data-spm="888">
    <div class="container-inner" data-role="content">
    </div>

</div>
<div class="industry-floor-box">

    <!--TMS:1906423-->
    <?php if ($manufacturer) {

        foreach ($manufacturer as $key => $manu) { ?>
            <div class="container industry-floor industry-floor-<?php echo $array_icon[$key] ?> "
                 id="j-industry-floor-<?php echo $array_icon[$key] ?>"
                 data-path="industry-<?php echo $array_icon[$key] ?>-floor">


                <div class="container-inner clearfix" data-spm="1">
                    <div class="indutry-info col-lg-10 col-md-12 col-sm-20">
                        <div class="industry-enter">
                            <a href="<?php echo $this->url->get("manufacturer/").$manu->ma_id ?>"><?php echo $manu->ma_name ?></a>
                        </div>
                        <div class="keyword-list">
                            <?php if (count($manu->CategoryModel) > 0) { ?>
                                <?php $categories = $manu->getCategory();
                                foreach ($categories as $key => $val) { ?>
                                    <a <?php if ($key % 2 == 0) { ?> class="highlight" <?php } ?>
                                        href="<?php echo $this->url->get("category-product/show/").$val->ct_seo_link ?>"><?php echo $val->ct_name ?></a>
                                <?php }
                            } ?>
                        </div>
                    </div>
                    <?php $products = $manu->getProduct(); ?>
                    <div class="recommend-box col-lg-20 col-md-24 hidden-sm">
                        <div class="recommend-slider-box">
                            <ul class="slides">
                                <?php if (count($products) > 0) {
                                    foreach ($products as $key => $pro) {
                                        if ($key <= 3) { ?>
                                            <li>
                                                <a href="<?php echo $this->url->get("product/show/") . $pro->pr_seo_link ?>">
                                                    <img src="<?php echo $pro->showImage() ?>" alt="">
                                                    <div class="event-info">
                                                        <span class="main-title"><?php echo $pro->pr_name ?></span>
                                                        <p class="sub-title"><?php echo $pro->getMinimumPrice() ?></p>
                                                    </div>
                                                </a>
                                            </li>
                                        <?php }
                                    }
                                } ?>
                            </ul>
                        </div>

                    </div>

                    <div class="rec-industry-right-list col-lg-10 col-md-12 hidden-sm hidden-md">
                        <ul>
                            <?php if (count($products) > 0) {
                                foreach ($products as $key => $pro) {
                                    if ($key > 3 && $key <= 5) { ?>
                                        <li>
                                            <a href="<?php echo $this->url->get("product/show/") . $pro->pr_seo_link ?>">
                                                <span class="subject"><?php echo $pro->pr_name ?></span>
                                                <span class="sub-heading"><?php echo $pro->getMinimumPrice() ?></span>
                                                <div class="pic">
                                                    <img src="<?php echo $pro->showImage() ?>" alt="" height="195"
                                                         width="180">
                                                </div>
                                            </a>
                                        </li>
                                    <?php }
                                }
                            } ?>

                        </ul>
                    </div>
                    <div class="rec-industry-right-list col-lg-10 col-md-12 hidden-sm hidden-md">
                        <ul>
                            <?php if (count($products) > 0) {
                                foreach ($products as $key => $pro) {
                                    if ($key > 5 && $key <= 7) { ?>
                                        <li>
                                            <a href="<?php echo $this->url->get("product/show/") . $pro->pr_seo_link ?>">
                                                <span class="subject"><?php echo $pro->pr_name ?></span>
                                                <span class="sub-heading"><?php echo $pro->getMinimumPrice() ?></span>
                                                <div class="pic">
                                                    <img src="<?php echo $pro->showImage() ?>" alt="" height="195"
                                                         width="180">
                                                </div>
                                            </a>
                                        </li>
                                    <?php }
                                }
                            } ?>

                        </ul>
                    </div>
                    <div class="rec-industry-right-list col-lg-10 col-md-12 hidden-sm hidden-md">
                        <ul>
                            <?php if (count($products) > 0) {
                                foreach ($products as $key => $pro) {
                                    if ($key > 7 && $key <= 9) { ?>
                                        <li>
                                            <a href="<?php echo $this->url->get("product/show/") . $pro->pr_seo_link ?>">
                                                <span class="subject"><?php echo $pro->pr_name ?></span>
                                                <span class="sub-heading"><?php echo $pro->getMinimumPrice() ?></span>
                                                <div class="pic">
                                                    <img src="<?php echo $pro->showImage() ?>" alt="" height="195"
                                                         width="180">
                                                </div>
                                            </a>
                                        </li>
                                    <?php }
                                }
                            } ?>

                        </ul>
                    </div>
                </div>
            </div>
        <?php }
    } ?>

</div>
<!--TMS:1715884-->
<div data-widget-cid="widget-23" class="container related-recommend" id="j-related-recommend" data-spm="13">
    <div class="container-inner">
        <div class="title"><h2>Recommendations for you</h2></div>
        <ul data-requestid="20160424211420252-74673138" class="product-list clearfix" data-role="product-container">
            <?php if ($productSaleRandom) {
                foreach ($productSaleRandom as $key => $prsale) { ?>
                    <li class="col-lg-12 col-md-15 col-sm-20">
                        <div class="item-inner">
                            <a href="<?php echo $this->url->get("product/show/") . $prsale->pr_seo_link ?>"
                               target="_blank">
                                <div class="pro-img"><i></i><img
                                        src="<?php echo $prsale->showImage() ?>">
                                </div>
                                <div class="pro-info">
                                    <div class="g-orders">133 Orders</div>
                                    <span class="g-price"><?php echo $prsale->showPricePromotion() ?></span>
                                    <del class="g-del-price"><?php echo $prsale->getMinimumPrice() ?></del>
                                </div>
                            </a>
                        </div>
                    </li>
                <?php }
            } ?>
        </ul>
    </div>

</div>  <!--TMS:1715913-->
<?php echo $this->partial('index/menu_scroll_left') ?>