<!--Product list mobile-->
<section id="today-deals" class="promotion-block today-deals" data-num="20" data-isgagaurl="">
    <header>
        <a>Sản Phẩm</a>
    </header>
    <article>
        <div style="display: none;" class="loading"></div>
        <ul class="util-clearfix product-container list-product-mobile">
            <?php if ($product) {
                foreach ($product as $pro) { ?>
                    <li>
                        <a href="<?php echo $this->url->get("product/show/") . $pro->pr_seo_link ?>">
                            <div class="product-image"><img
                                    src="<?php echo $pro->showImage() ?>">
                            </div>
                            <?php if ($pro->showPricePromotion()) { ?>
                                <div class="product-cost"><b><?php echo $pro->showPricePromotion() ?></b></div>
                                <del class="g-del-price"><?php echo $pro->getMinimumPrice() ?></del>
                            <?php } else { ?>
                                <div class="product-cost"><b><?php echo $pro->getMinimumPrice() ?></b></div>
                            <?php } ?>
                            <div class="product-cost">Đã bán (<?php echo $pro->countOrder() ?>)</div>
                        </a>
                    </li>
                <?php }
            } ?>

        </ul>
    </article>
    <div class="md-loading" style="display: none">
        <div class="preloader-wrapper active">
            <div class="spinner-layer spinner-red-only">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div><div class="gap-patch">
                    <div class="circle"></div>
                </div><div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
    </div>
    <a href="javascript:;" id="load-more-product-mobile" class="ui-button ui-button-third">View
        more&nbsp;</a>
</section>
<!--End product list mobile-->