<!--Sale Product Mobile-->
<section class="promotion-block top-spread">
    <article>
        <ul class="flex-box top-spread-2">
            <li>
                <a data-spm-anchor-id="0.0.0.0" href="http://m.aliexpress.com/column/flashdeals.htm?fromapp=false"
                   style="position:relative;" id="flash-deal-floor">
                    <img
                        src="<?php echo $this->url->get("public/FrontendCore/") ?>img/HTB1nrh_LFXXXXXuXXXXq6xXFXXXA.jpg">
                    <p style="position:absolute;left:7%;top:3%;line-height:14px;font-size:15px;color:#E87644;margin:0;max-width:86%;text-overflow:ellipsis;overflow:hidden;white-space:nowrap;">
                        Flash Deals</p>
                    <div style="display: block;" class="countdown">

                    </div>
                </a>
            </li>
            <li>
                <a data-spm-anchor-id="0.0.0.0" href="http://activities.aliexpress.com/superdeals_mobile.php"
                   style="position:relative;">
                    <img
                        src="<?php echo $this->url->get("public/FrontendCore/") ?>img/TB1CcuOFVXXXXcDXFXXtXFo3FXX-296-264.jpg">
                    <p style="position:absolute;left:7%;top:3%;line-height:14px;font-size:15px;color:#6A7181;margin:0;max-width:86%;text-overflow:ellipsis;overflow:hidden;white-space:nowrap;">
                        Super Deals</p></a>
            </li>

        </ul>
    </article>
</section>
<!-- End Sale Product Mobile-->