<div class="wrapper">
    <div style="margin-top: 20px" id="category-product" class="main-content-area">
        <?php
        if (count($product)>0) {
            foreach ($product as $pro) {
                ?>
                <div class="productListItem productList__item productList__cols-A1">
                    <a class="productListLink productList__link"
                       href="<?php echo $this->url->get() . "product/show/" . $pro->pr_seo_link; ?>">
                        <div class="productList__img  visible">
                            <img class="productListImg hasHover lazy-loaded" src="<?php echo $pro->showImage() ?>"
                                 alt="">
                            <img class="productListImgHover lazy-loaded" src="<?php echo $pro->showImageHover() ?>"
                                 alt="">
                        </div>
                        <div class="productList__info">
                                <span class="productList__name"><span
                                        class="new-product">Hàng Mới</span> <?php echo $pro->pr_name ?></span>
                            <?php $pricePromotion = $pro->showPricePromotion();
                            if ($pricePromotion) { ?>
                                <span style="font-size: 16px;"
                                      class="productList__price"><?php echo $pro->showPricePromotion(); ?></span>
                                <span style="text-decoration: line-through"
                                      class="productList__price"><?php echo $pro->showPrice(); ?></span>
                            <?php } else { ?>
                                <span class="productList__price"><?php echo $pro->showPrice(); ?></span>
                            <?php } ?>
                        </div>
                    </a>
                    <?php
                    $listColor = $pro->showColor();
                    if (!empty($listColor)) {
                        ?>
                        <div class="product-list-colors">
                            <?php
                            foreach ($listColor as $color) {
                                ?>
                                <div class="color ">
                                    <a href="javascript:;" class="other-color"
                                       style="background-color: <?php echo $color->plo_detail ?>"></a>
                                </div>
                                <?php
                            }
                            ?>
                            <span class="productList__moreColors">  Màu Khác</span>
                        </div>
                    <?php } ?>
                </div>
                <?php
            }
        } else {
            echo "<h1 style='font-size: 20px; text-align: center; margin: 20px 0px;' >Không có sản phẩm với từ khóa '" . $keyword . "'</h1>";
        }
        ?>
        <div class="clearfix"></div>
    </div>
</div>