<div id="page" class="categories-collapse autosize_wrap en-us">
    <div class="grid-c2-s5 util-clearfix">
        <div class="col-main">
            <div style="margin: 0" id="main-wrap" class="main-wrap gallery-mode">


                <div class="container">
                    <?php if (count($products->items)>0) { ?>
                        <div id="list-items" class="clearfix temp-height lazy-load" data - spm="3">

                            <ul class="util-clearfix son-list">


                                <?php foreach ($products->items as $product) { ?>
                                    <li class="list-item list-item-first ">
                                        <div class="item">
                                            <div class="img img-border">
                                                <div class="pic">
                                                    <a class="picRind "
                                                       href="<?php echo $this->url->get("product/show/") . $product->pr_seo_link ?>">
                                                        <img class="picCore pic-Core-v"
                                                             src="<?php echo $product->showImage() ?>"
                                                             alt="<?php echo $product->pr_name ?>">
                                                    </a>
                                                </div>
                                            </div>


                                            <div class="info">
                                                <h3>
                                                    <a class="product "
                                                       href="<?php echo $this->url->get("product/show/") . $product->pr_seo_link ?>"
                                                       title="<?php echo $product->pr_name ?>"><?php echo $product->pr_name ?>
                                                    </a>
                                                </h3>
                                                <?php if ($product->showPricePromotion()) { ?>
                                                    <span class="price price-m">
                                                        <span class="value"
                                                              itemprop="price"><?php echo $product->showPricePromotion() ?></span>
                                                    </span>
                                                    <div>
                                                        <del
                                                            class="original-price"> <?php echo $product->getMinimumPrice() ?></del>
                                                    </div>
                                                <?php } else { ?>
                                                    <span class="price price-m"><span class="value"
                                                                                      itemprop="price"><?php echo $product->getMinimumPrice() ?></span></span>
                                                <?php } ?>
                                                <div class="rate-history">
                                                        <span style="float:right" rel="nofollow" class="order-num">
                                                            <a class="order-num-a " href="javascript:;" rel="nofollow">
                                                                <em title="Total Orders"> Đã bán (<?php echo $product->countOrder() ?>
                                                                    )</em>
                                                            </a>
                                                        </span>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                <?php }
                                ?>
                            </ul>
                        </div>
                        <div data-widget-cid="widget-10" id="pagination-bottom"
                             class="ui-pagination ui-pagination-front ui-pagination-body util-clearfix"
                             data-spm-protocol="i">
                            <div class="ui-pagination-navi util-left">
                                <a href="<?php echo $this->url->get() . "search?key=" . $keyword . "&page=" . $products->before ?>"
                                   class="ui-pagination-prev ui-pagination-disabled">Previous</a>
                                <?php for ($i = 1; $i <= $products->total_pages; $i++) { ?>
                                    <a <?php if ($products->current == $i) {
                                        echo ' class="ui-pagination-active" ';
                                    } ?>
                                        href="<?php echo $this->url->get() . "search?key=" . $keyword . "&page=" . $i ?>">
                                        <?php echo $i; ?>
                                    </a>
                                <?php } ?>
                                <a href="<?php echo $this->url->get() . "search?key=" . $keyword . "&page=" . $products->next ?>"
                                   class="page-next ui-pagination-next">Next</a>
                            </div>
                        </div>
                    <?php } else {
                        echo "<h1 style='font-size: 20px; text-align: center; margin: 20px 0px;' >Không có sản phẩm với từ khóa '" . $keyword . "'</h1>";
                    } ?>

                </div>

            </div>
        </div>
    </div>
</div>