<div  class="wrapper">
    <div class="sizeguide-header">
        <h1>Làm thế nào để biết được size của mình?</h1>
        <a class="btn-print" href="javascript:;"><i class="fa fa-print fa-2x" aria-hidden="true"></i> </a>
    </div>
    <div class="sizeguide-main-area">
        <img src="<?php echo $product->pr_image_sizeguide ?>" alt="">
        <p>* The measurements in the guide are based on measurements taken directly from the body, not the garment. If your measurement is between two sizes, we recommend you select the larger size.</p>
    </div>
</div>