<!-- Main content -->
<div class="content-wrapper">

    <!-- Page header -->
    <div class="page-header">
        <div class="page-header-content">
            <div class="page-title">
                <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Home</span> - Dashboard</h4>
            </div>

            <div class="heading-elements">
                <div class="heading-btn-group">
                    <a href="#" class="btn btn-link btn-float has-text"><i class="icon-bars-alt text-primary"></i><span>Statistics</span></a>
                    <a href="#" class="btn btn-link btn-float has-text"><i class="icon-calculator text-primary"></i> <span>Invoices</span></a>
                    <a href="#" class="btn btn-link btn-float has-text"><i class="icon-calendar5 text-primary"></i> <span>Schedule</span></a>
                </div>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li><a href="index.html"><i class="icon-home2 position-left"></i> Home</a></li>
                <li><a href="index.html">Home</a></li>
                <li class="active">Dashboard</li>
            </ul>

            <ul class="breadcrumb-elements">
                <li><a href="#"><i class="icon-comment-discussion position-left"></i> Support</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-gear position-left"></i>
                        Settings
                        <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu dropdown-menu-right">
                        <li><a href="#"><i class="icon-user-lock"></i> Account security</a></li>
                        <li><a href="#"><i class="icon-statistics"></i> Analytics</a></li>
                        <li><a href="#"><i class="icon-accessibility"></i> Accessibility</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="icon-gear"></i> All settings</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <!-- /page header -->


    <!-- Content area -->
    <div class="content">
        <div class="row">
            <div class="col-lg-4">

                <!-- Members online -->
                <div style="border: #00695C solid 1px;" class="panel">
                    <div style="color:#00695C " class="panel-body">
                        <div class="heading-elements">
                            <a href="<?php echo $this->url->get("backend/order") ?>" style="font-size: 15px;" class="heading-text badge bg-teal-800"><span class="nu-today-order-new" ></span> New</a>
                        </div>

                        <h3 class="no-margin nu-today-order">0</h3>
                        Today Orders 
                    </div>

                    <div class="container-fluid">
                        <div class="today-orders"></div>
                    </div>
                </div>
                <!-- /members online -->

            </div>

            <div class="col-lg-4">

                <!-- Current server load -->
                <div style="border: #EC407A solid 1px;" class="panel ">
                    <div style="color:#EC407A " class="panel-body">

                        <h3 class="no-margin"><span class="nu-today-sale" ></span> VNĐ</h3>
                        Today Sales 
                    </div>

                    <div class="container-fluid">
                        <div class="today-sales"></div>
                    </div>
                </div>
                <!-- /current server load -->

            </div>

            <div class="col-lg-4">

                <!-- Today's revenue -->

                <div style="border: #29B6F6 solid 1px;" class="panel ">
                    <div style="color:#29B6F6 " class="panel-body">

                        <h3 class="no-margin nu-today-customers"></h3>
                        Today New Customers
                    </div>

                    <div class="container-fluid">
                        <div class="today-customers"></div>
                    </div>
                </div>
                <!-- /today's revenue -->

            </div>
        </div>
        <!-- Main charts -->
        <div class="row">
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">Charts Orders Statistic</h5>
                    <div class="heading-elements">
                        <form onsubmit="return false;" class="form-order-statistic-month">
                            <div class="col-md-1">
                                <label style="position: relative; top: 8px; left: -10px;">Month </label>
                            </div>
                            <div class="col-md-4">
                                <select style="width: 50px"  name="month" class="select-search">
                                    <option value="-1">Chose</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                    <option value="11">11</option>
                                    <option value="12">12</option>
                                </select>
                            </div>
                            <div class="col-md-1">
                                <label style="position: relative; top: 8px;">Year </label>
                            </div>
                            <div class="col-md-4">
                                <select  name="year" class="select-search">
                                    <option value="-1">Chose</option>
                                    <?php foreach ($year as $ye) { ?>
                                        <option value="<?php echo $ye->time ?>" ><?php echo $ye->time ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <button onclick="filterStatistic('form-order-statistic-month', 'get-month-order', 'order-statistic-month');" style="width: 70px;" type="submit" class="btn btn-block btn-primary btn-statistic-order-month">Filter</button>
                            </div>

                        </form>
                    </div>
                </div>

                <div class="panel-body">
                    <div class="chart-container">
                        <div class="chart has-fixed-height" id="order-statistic-month"></div>
                    </div>
                </div>
            </div>
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">Charts Sales Statistic</h5>
                    <div class="heading-elements">
                        <form onsubmit="return false;" class="form-sale-statistic-month">
                            <div class="col-md-1">
                                <label style="position: relative; top: 8px; left: -10px;">Month </label>
                            </div>
                            <div class="col-md-4">
                                <select style="width: 50px"  name="month" class="select-search">
                                    <option value="-1">Chose</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                    <option value="11">11</option>
                                    <option value="12">12</option>
                                </select>
                            </div>
                            <div class="col-md-1">
                                <label style="position: relative; top: 8px;">Year </label>
                            </div>
                            <div class="col-md-4">
                                <select  name="year" class="select-search">
                                    <option value="-1">Chose</option>
                                    <?php foreach ($year as $ye) { ?>
                                        <option value="<?php echo $ye->time ?>" ><?php echo $ye->time ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <button onclick="filterStatistic('form-sale-statistic-month', 'get-month-sale', 'sales-statistic-month');" style="width: 70px;" type="submit" class="btn btn-block btn-primary btn-statistic-order-month">Filter</button>
                            </div>

                        </form>
                    </div>
                </div>

                <div class="panel-body">
                    <div class="chart-container">
                        <div class="chart has-fixed-height" id="sales-statistic-month"></div>
                    </div>
                </div>
            </div>
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">Charts Customers Statistic</h5>
                    <div class="heading-elements">
                        <form onsubmit="return false;" class="form-user-statistic-month">
                            <div class="col-md-1">
                                <label style="position: relative; top: 8px; left: -10px;">Month </label>
                            </div>
                            <div class="col-md-4">
                                <select style="width: 50px"  name="month" class="select-search">
                                    <option value="-1">Chose</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                    <option value="11">11</option>
                                    <option value="12">12</option>
                                </select>
                            </div>
                            <div class="col-md-1">
                                <label style="position: relative; top: 8px;">Year </label>
                            </div>
                            <div class="col-md-4">
                                <select  name="year" class="select-search">
                                    <option value="-1">Chose</option>
                                    <?php foreach ($year as $ye) { ?>
                                        <option value="<?php echo $ye->time ?>" ><?php echo $ye->time ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <button onclick="filterStatistic('form-user-statistic-month', 'get-month-user', 'customer-statistic-month');" style="width: 70px;" type="submit" class="btn btn-block btn-primary btn-statistic-order-month">Filter</button>
                            </div>

                        </form>
                    </div>
                </div>

                <div class="panel-body">
                    <div class="chart-container">
                        <div class="chart has-fixed-height" id="customer-statistic-month"></div>
                    </div>
                </div>
            </div>
        </div>



        <!-- Footer -->
<!--        <div class="footer text-muted">
            &copy; 2015. <a href="#">Limitless Web App Kit</a> by <a href="http://themeforest.net/user/Kopyov" target="_blank">Eugene Kopyov</a>
        </div>-->
        <!-- /footer -->

    </div>
    <!-- /content area -->

</div>
<!-- /main content -->
