<div class="site-server-box" data-site="site" data-spm="20">
    <div class="container">
        <div class="site-item">
            <i class="icon i-great"></i>
            <h3>Great Value</h3>
            <p>We offer competitive prices on our 100 million plus product range.</p>
        </div>
        <div class="site-item">
            <i class="icon i-delivery"></i>
            <h3>Worldwide Delivery</h3>
            <p>With sites in 5 languages, we ship to over 200 countries &amp; regions.</p>
        </div>
        <div class="site-item">
            <i class="icon i-payment"></i>
            <h3>Safe Payment</h3>
            <p>Pay with the world’s most popular and secure payment methods.</p>
        </div>
        <div class="site-item">
            <i class="icon i-confidence"></i>
            <h3>Shop with Confidence</h3>
            <p>Our Buyer Protection covers your purchase from click to delivery.</p>
        </div>
        <div class="site-item">
            <i class="icon i-help"></i>
            <h3>24/7 Help Center</h3>
            <p>Round-the-clock assistance for a smooth shopping experience.</p>
        </div>
        <div class="site-item">
            <i class="icon i-shop"></i>
            <h3>Shop On-The-Go</h3>
            <p><a rel="nofollow" href="http://sale.aliexpress.com/__pc/download_app_guide.htm">Download the app</a> and
                get the world of AliExpress at your fingertips.</p>
        </div>
    </div>
</div>  <!--TMS:1715941-->
<div class="user-helper-footer" data-spm="14">
    <div class="container">
        <div class="col-sm-30 col-md-30 col-lg-24">
            <div data-widget-cid="widget-22" class="alert-subscribe-form" id="alert-subscribe-form"
                 data-failtips="Oops, subscribe unsuccessful. Please try again."
                 data-successtips="&lt;em&gt;Congratulations!&lt;/em&gt;You have successfully subscribed."
                 data-emailerror="Invalid email address. Please try again.">
                <h3>Subscription</h3>
                <form onsubmit=" registerNewsletter(); return false; " method="post"
                      class="form-newsletter form-horizontal">
                    <input type="hidden" name="us_newsletter" value="1">
                    <input type="hidden" name="us_status" value="0">
                    <input type="hidden" name="us_from" value="1">
                    <input email="true" required="true" name="us_email" placeholder="Please enter your email" class="alert-subscribe-input" data-role="input"
                           type="text">
                    <button onclick="registerNewsletter();" type="button" class="alert-subscribe-submit">Subscribe
                    </button>
                    <input style="visibility: hidden;position: absolute;" type="submit">
                </form>
                <p class="tips">Register now to get updates on promotions and coupons.</p>
            </div>
            <div class="app-box">
                <div class="social-networks">
                    <h3>Stay Connected</h3>
                    <div class="foot-sns-box">
                        <a rel="nofollow" target="_blank" class="fb" href="https://www.facebook.com/shopaliexpress"></a>
                        <a rel="nofollow" target="_blank" href="https://vk.com/aliexpress" class="vk"></a>
                        <a rel="nofollow" target="_blank" href="http://ok.ru/officialaliexpress" class="ok"></a>
                        <a rel="nofollow" target="_blank" href="https://twitter.com/AliexpressR" class="twitter"></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-15 col-md-15 col-lg-12">
            <h3 class="f-link-header">How to Buy</h3>
            <ul class="f-link-list">
                <li><a href="https://login.aliexpress.com/join/buyer/expressJoin.htm" rel="nofollow">Create an
                        Account</a></li>
                <li><a href="http://help.aliexpress.com/categories_Payment.html" rel="nofollow">Making Payments</a></li>
                <li><a href="http://help.aliexpress.com/shipping_methods.html" rel="nofollow">Delivery Options</a></li>
                <li><a href="http://activities.aliexpress.com/adcms/www-aliexpress-com/buyerprotection/index.php"
                       rel="nofollow">Buyer Protection</a></li>
                <li><a href="http://www.aliexpress.com/how-to-buy" rel="nofollow">New User Guide</a></li>
            </ul>
        </div>
        <div class="col-sm-15 col-md-15 col-lg-12">
            <h3 class="f-link-header">Customer Service</h3>
            <ul class="f-link-list">
                <li><a href="http://www.aliexpress.com/help/contactus.htm" rel="nofollow">Customer Service</a></li>
                <li><a href="http://rule.alibaba.com/rule/detail/2054.htm" rel="nofollow">Transaction Service
                        Agreement</a></li>
                <li><a href="https://www.surveymonkey.com/r/?sm=9z9qYkOd%2fEnXROEaWLxcOUt4dfPTFY7TGg0vXOC6XnQ%3d"
                       rel="nofollow">Take Our Survey</a></li>
                <li><a href="http://activities.aliexpress.com/contactus.php" rel="nofollow">Organization &amp; Technical
                        Support</a></li>
            </ul>
        </div>
        <div class="col-lg-12 hidden-md hidden-sm">
            <h3 class="f-link-header">Partner Promotion</h3>
            <ul class="f-link-list">
                <li><a href="http://www.alibabagroup.com/en/global/home" rel="nofollow">Partnerships</a></li>
                <li><a href="http://portals.aliexpress.com/" rel="nofollow">Affiliate Program</a></li>
            </ul>
            <h3 class="f-link-header"></h3>
            <ul class="f-link-list">
            </ul>
        </div>
    </div>
</div>  <!--TMS:1715997-->
<div class="partner-box">
    <div class="container">
        <div class="partner-list">
            <span class="partner-1"></span><span class="partner-2"></span><span class="partner-3"></span><span
                class="partner-4"></span><span class="partner-5"></span><span class="partner-6"></span><span
                class="partner-7"></span><span class="partner-8"></span><span class="partner-9"></span><span
                class="partner-10"></span><span class="partner-11"></span><span class="partner-12"></span><span
                class="partner-13"></span><span class="partner-14"></span><span class="partner-15"></span><span
                class="partner-16"></span><span class="partner-17"></span><span class="partner-18"></span><span
                class="partner-19"></span><span class="partner-20"></span><span class="partner-21"></span>
        </div>
    </div>
</div>  <!--TMS:1909889-->

<!--TMS:1525835-->
<!--START TMS:1858189-->

<div class="footer-copywrite">
    <div class="container">
        <b>AliExpress™</b>© 2010-2015 AliExpress.com. All rights reserved.
    </div>
</div>
<div class="m-footer-main">
    <div class="footer-field">
        <p class="title">Payment Methods:</p>
        <div class="payment-container">
            <img src="<?php echo $this->url->get("public/FrontendCore/") ?>img/TB1dBf3GVXXXXaSXpXXMY_7NFXX-608-178.png" alt="Payment Methods"></div>
    </div>
    <footer class="ms-footer">
        <div class="copyright">
            <div>
                <p><a rel="nofollow" href="//news.alibaba.com/article/detail/help/100453303-1-privacy-policy.html">Privacy
                        Policy&nbsp;</a> - <a rel="nofollow"
                                              href="//news.alibaba.com/article/detail/help/100453293-1-terms-use.html">Terms
                        of use&nbsp;</a> - <a href="http://m.aliexpress.com/sitemap.html">Site Map</a>
                </p>

                <!--anita-if-->
                <!--anita-if-->
            </div>

            <p>© 2010-2015 <a href="//m.aliexpress.com/website.html" class="text-link"
                              data-stat="front_page::aecom::aecom_button">AliExpress.com</a>. All rights reserved.</p>
        </div>
    </footer>
</div>