<div class="site-server-box" data-site="site" data-spm="20">
    <div class="container">
        <div class="site-item">
            <i class="icon i-great"></i>
            <h3>Great Value</h3>
            <p>We offer competitive prices on our 100 million plus product range.</p>
        </div>
        <div class="site-item">
            <i class="icon i-delivery"></i>
            <h3>Worldwide Delivery</h3>
            <p>With sites in 5 languages, we ship to over 200 countries &amp; regions.</p>
        </div>
        <div class="site-item">
            <i class="icon i-payment"></i>
            <h3>Safe Payment</h3>
            <p>Pay with the world’s most popular and secure payment methods.</p>
        </div>
        <div class="site-item">
            <i class="icon i-confidence"></i>
            <h3>Shop with Confidence</h3>
            <p>Our Buyer Protection covers your purchase from click to delivery.</p>
        </div>
        <div class="site-item">
            <i class="icon i-help"></i>
            <h3>24/7 Help Center</h3>
            <p>Round-the-clock assistance for a smooth shopping experience.</p>
        </div>
        <div class="site-item">
            <i class="icon i-shop"></i>
            <h3>Shop On-The-Go</h3>
            <p><a rel="nofollow" href="http://sale.aliexpress.com/__pc/download_app_guide.htm">Download the app</a> and
                get the world of AliExpress at your fingertips.</p>
        </div>
    </div>
</div>  <!--TMS:1715941-->
<div class="user-helper-footer" data-spm="14">
    <div class="container">
        <div class="col-sm-30 col-md-30 col-lg-24">
            <div data-widget-cid="widget-22" class="alert-subscribe-form" id="alert-subscribe-form"
                 data-failtips="Oops, subscribe unsuccessful. Please try again."
                 data-successtips="&lt;em&gt;Congratulations!&lt;/em&gt;You have successfully subscribed."
                 data-emailerror="Invalid email address. Please try again.">
                <h3>Subscription</h3>
                <input placeholder="Please enter your email" class="alert-subscribe-input" data-role="input"
                       type="text"><input value="Subscribe" class="alert-subscribe-submit" data-role="submit"
                                          type="submit">
                <div class="email-error-tips"></div>
                <p class="tips">Register now to get updates on promotions and coupons.</p>
            </div>
            <div class="app-box">
                <div class="social-networks">
                    <h3>Stay Connected</h3>
                    <div class="foot-sns-box">
                        <a rel="nofollow" target="_blank" class="fb" href="https://www.facebook.com/shopaliexpress"></a>
                        <a rel="nofollow" target="_blank" href="https://vk.com/aliexpress" class="vk"></a>
                        <a rel="nofollow" target="_blank" href="http://ok.ru/officialaliexpress" class="ok"></a>
                        <a rel="nofollow" target="_blank" href="https://twitter.com/AliexpressR" class="twitter"></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-15 col-md-15 col-lg-12">
            <h3 class="f-link-header">How to Buy</h3>
            <ul class="f-link-list">
                <li><a href="https://login.aliexpress.com/join/buyer/expressJoin.htm" rel="nofollow">Create an
                        Account</a></li>
                <li><a href="http://help.aliexpress.com/categories_Payment.html" rel="nofollow">Making Payments</a></li>
                <li><a href="http://help.aliexpress.com/shipping_methods.html" rel="nofollow">Delivery Options</a></li>
                <li><a href="http://activities.aliexpress.com/adcms/www-aliexpress-com/buyerprotection/index.php"
                       rel="nofollow">Buyer Protection</a></li>
                <li><a href="http://www.aliexpress.com/how-to-buy" rel="nofollow">New User Guide</a></li>
            </ul>
        </div>
        <div class="col-sm-15 col-md-15 col-lg-12">
            <h3 class="f-link-header">Customer Service</h3>
            <ul class="f-link-list">
                <li><a href="http://www.aliexpress.com/help/contactus.htm" rel="nofollow">Customer Service</a></li>
                <li><a href="http://rule.alibaba.com/rule/detail/2054.htm" rel="nofollow">Transaction Service
                        Agreement</a></li>
                <li><a href="https://www.surveymonkey.com/r/?sm=9z9qYkOd%2fEnXROEaWLxcOUt4dfPTFY7TGg0vXOC6XnQ%3d"
                       rel="nofollow">Take Our Survey</a></li>
                <li><a href="http://activities.aliexpress.com/contactus.php" rel="nofollow">Organization &amp; Technical
                        Support</a></li>
            </ul>
        </div>
        <div class="col-lg-12 hidden-md hidden-sm">
            <h3 class="f-link-header">Partner Promotion</h3>
            <ul class="f-link-list">
                <li><a href="http://www.alibabagroup.com/en/global/home" rel="nofollow">Partnerships</a></li>
                <li><a href="http://portals.aliexpress.com/" rel="nofollow">Affiliate Program</a></li>
            </ul>
            <h3 class="f-link-header"></h3>
            <ul class="f-link-list">
            </ul>
        </div>
    </div>
</div>  <!--TMS:1715997-->
<div class="partner-box">
    <div class="container">
        <div class="partner-list">
            <span class="partner-1"></span><span class="partner-2"></span><span class="partner-3"></span><span
                class="partner-4"></span><span class="partner-5"></span><span class="partner-6"></span><span
                class="partner-7"></span><span class="partner-8"></span><span class="partner-9"></span><span
                class="partner-10"></span><span class="partner-11"></span><span class="partner-12"></span><span
                class="partner-13"></span><span class="partner-14"></span><span class="partner-15"></span><span
                class="partner-16"></span><span class="partner-17"></span><span class="partner-18"></span><span
                class="partner-19"></span><span class="partner-20"></span><span class="partner-21"></span>
        </div>
    </div>
</div>  <!--TMS:1909889-->

<!--TMS:1525835-->
<!--START TMS:1858189-->
<div class="site-footer">
    <div class="container">
        <div class="sf-aliexpressInfo clearfix">
            <div class="sf-siteIntro col-lg-30 col-md-30 col-sm-60">
                <dl>
                    <dt>AliExpress Information</dt>
                    <dd>
                        <a href="http://www.aliexpress.com/about.html">About AliExpress</a>, <a
                            href="http://www.aliexpress.com/sitemap.html">Site Map</a>, <a
                            href="http://www.aliexpress.com/">Online Shopping</a>, <a
                            href="http://www.aliexpress.com/all-wholesale-products.html">Buy</a>, <a
                            href="https://login.aliexpress.com/?returnUrl=http%3A%2F%2Ftrade.aliexpress.com%2ForderList.htm%3Ftsp%3D1432889415882"
                            ref="nofollow">My Orders</a>, <a href="http://www.aliexpress.com/help/home.html"
                                                             ref="nofollow">Help Center</a>, <a
                            href="http://www.aliexpress.com/help/contactus.htm" ref="nofollow">Customer Support</a>, <a
                            href="http://seller.aliexpress.com/" ref="nofollow">AliExpress Seller Center</a>, <a
                            href="http://m.aliexpress.com/">Mobile Site</a></dd>
                </dl>
            </div>
            <div class="sf-MultiLanguageSite col-lg-30 col-md-30 col-sm-60">
                <dl>
                    <dt>AliExpress Multi-Language Sites</dt>
                    <dd>
                        <a href="http://ru.aliexpress.com/">Russian</a>, <a
                            href="http://pt.aliexpress.com/">Portuguese</a>, <a
                            href="http://es.aliexpress.com/">Spanish</a>, <a href="http://fr.aliexpress.com/">French</a>,
                        <a href="http://id.aliexpress.com/">Indonesian</a>, <a
                            href="http://de.aliexpress.com/">German</a>, <a href="http://it.aliexpress.com/">Italian</a>,
                        <a href="http://nl.aliexpress.com/">Dutch</a>, <a href="http://tr.aliexpress.com/">Turkish</a>,
                        <a href="http://ja.aliexpress.com/">Japanese</a>, <a href="http://ko.aliexpress.com/">Korean</a>,
                        <a href="http://th.aliexpress.com/">Thai</a>, <a href="http://vi.aliexpress.com/">Vietnamese</a>,
                        <a href="http://ar.aliexpress.com/">Arabic</a>, <a href="http://he.aliexpress.com/">Hebrew</a>,
                        <a href="http://pl.aliexpress.com/">Polish</a></dd>
                </dl>
            </div>
        </div>

        <div class="sf-seoKeyword col-lg-30 col-md-30 col-sm-60">
            <dl>
                <dt>Browse by Category</dt>
                <dd>
                    <a href="http://www.aliexpress.com/popular.html">All Popular</a>, <a
                        href="http://www.aliexpress.com/wholesale.html">Product</a>, <a
                        href="http://www.aliexpress.com/promotion.html">Promotion</a>, <a
                        href="http://www.aliexpress.com/price.html">Low Price</a>, <a
                        href="http://www.aliexpress.com/cheap.html">Great Value</a>, <a
                        href="http://www.aliexpress.com/compare.html">Retail</a>, <a
                        href="http://www.aliexpress.com/reviews.html">Reviews</a>, <a
                        href="http://brands.aliexpress.com/">China Brands</a></dd>
            </dl>
        </div>
        <div class="sf-alibabaGroup col-lg-30 col-md-30 col-sm-60">
            <dl>
                <dt>Alibaba Group</dt>
                <dd>
                    <a href="http://www.alibabagroup.com/en/global/home" ref="nofollow">Alibaba Group Website</a>, <a
                        href="http://www.aliexpress.com/" ref="nofollow">AliExpress</a>, <a
                        href="http://www.alimama.com/" ref="nofollow">Alimama</a>, <a
                        href="https://intl.alipay.com/index.htm" ref="nofollow">Alipay</a>, <a
                        href="http://www.alitrip.com/" ref="nofollow">AliTravel</a>, <a href="http://www.alicloud.com/"
                                                                                        ref="nofollow">AliCloud</a>, <a
                        href="http://www.alibaba.com/" ref="nofollow">Alibaba International</a>, <a
                        href="http://aliqin.tmall.com/" ref="nofollow">Ali Telecom</a>, <a
                        href="http://www.dingtalk.com/" ref="nofollow">Ding Talk</a>, <a href="http://ju.taobao.com/"
                                                                                         ref="nofollow">Juhuasuan</a>,
                    <a href="http://www.laiwang.com/" ref="nofollow">LaiWang</a>, <a href="http://www.net.cn/"
                                                                                     ref="nofollow">Net.cn</a>, <a
                        href="http://www.taobao.com/" ref="nofollow">Taobao Markertplace</a>, <a
                        href="http://www.tmall.com/" ref="nofollow">Tmall</a>, <a href="http://www.xiami.com/"
                                                                                  ref="nofollow">Xiami</a>, <a
                        href="http://www.yunos.com/" ref="nofollow">YUN OS</a>, <a href="http://www.1688.com/"
                                                                                   ref="nofollow">1688</a></dd>
            </dl>
        </div>
        <div class="sf-download-app"><a class="android-link"
                                        href="https://play.google.com/store/apps/details?id=com.alibaba.aliexpresshd"
                                        ref="nofollow" target="_blank">Google Play</a><a class="iphone-link"
                                                                                         href="https://itunes.apple.com/us/app/aliexpress/id436672029"
                                                                                         target="_blank" ref="nofollow">App
                Store</a></div>
    </div>
</div>

<div class="footer-copywrite">
    <div class="container">
        <b>AliExpress™</b>© 2010-2015 AliExpress.com. All rights reserved.
    </div>
</div>
<div class="m-footer-main">
    <div class="footer-field">
        <p class="title">Learn More:</p>
        <a class="protection-container" href="http://www.aliexpress.com/buyerprotection/index.html" target="_blank"
           data-stat="front_page::buyerprotection::bp_button">
            <p class="protection-title">Buyer Protection</p>
            <p class="protection-item">
                Full refund if you don't receive your order
            </p>
            <p class="protection-item">
                Refund or keep items not as described
            </p>
            <span class="arrow"></span>
        </a>
        <a href="http://help.aliexpress.com/new_use_guide.html" class="user-guide" target="_blank"
           data-stat="front_page::newuserguide::nug_button">New User Guide<span class="arrow"></span>
        </a>
    </div>
    <div class="footer-field">
        <p class="title">Payment Methods:</p>
        <div class="payment-container">
            <img src="img/TB1dBf3GVXXXXaSXpXXMY_7NFXX-608-178.png" alt="Payment Methods"></div>
    </div>
    <footer class="ms-footer">
        <div class="copyright">
            <div>
                <p><a rel="nofollow" href="//news.alibaba.com/article/detail/help/100453303-1-privacy-policy.html">Privacy
                        Policy&nbsp;</a> - <a rel="nofollow"
                                              href="//news.alibaba.com/article/detail/help/100453293-1-terms-use.html">Terms
                        of use&nbsp;</a> - <a href="http://m.aliexpress.com/sitemap.html">Site Map</a>
                </p>

                <!--anita-if-->
                <!--anita-if-->
            </div>

            <p>© 2010-2015 <a href="//m.aliexpress.com/website.html" class="text-link"
                              data-stat="front_page::aecom::aecom_button">AliExpress.com</a>. All rights reserved.</p>
        </div>
    </footer>
</div>