<div data-spm-max-idx="13" data-widget-cid="widget-17"
     style="position: fixed; visibility: hidden; left: 311.5px; top: 120px;" class="floor-fixed-panel"
     id="j-floor-fixed-panel" data-spm="19">
    <ul class="floor-nav-list">
        <li class="nav-women"><a data-spm-anchor-id="2114.11010108.19.1" data-widget-cid="widget-18" class="current"
                                 href="#j-industry-floor-women"><i></i><span>Women's Clothing</span></a></li>
        <li class="nav-men"><a class="" data-spm-anchor-id="2114.11010108.19.2" data-widget-cid="widget-18"
                               href="#j-industry-floor-men"><i></i><span>Men’s Clothing</span></a></li>
        <li class="nav-phone "><a class="" data-spm-anchor-id="2114.11010108.19.3" data-widget-cid="widget-18"
                                  href="#j-industry-floor-phone"><i></i><span>Phones &amp; Accessories</span></a></li>
        <li class="nav-computer"><a class="" data-spm-anchor-id="2114.11010108.19.4" data-widget-cid="widget-18"
                                    href="#j-industry-floor-computer"><i></i><span>Computer &amp; Networking</span></a>
        </li>
        <li class="nav-electronics"><a class="" data-spm-anchor-id="2114.11010108.19.5" data-widget-cid="widget-18"
                                       href="#j-industry-floor-electronics"><i></i><span>Consumer Electronics</span></a>
        </li>
        <li class="nav-jewelry"><a class="" data-spm-anchor-id="2114.11010108.19.6" data-widget-cid="widget-18"
                                   href="#j-industry-floor-jewelry"><i></i><span>Jewelry &amp; Watches</span></a></li>
        <li class="nav-garden"><a class="" data-spm-anchor-id="2114.11010108.19.7" data-widget-cid="widget-18"
                                  href="#j-industry-floor-garden"><i></i><span>Home &amp; Garden</span></a></li>
        <li class="nav-bags"><a class="" data-spm-anchor-id="2114.11010108.19.8" data-widget-cid="widget-18"
                                href="#j-industry-floor-bags"><i></i><span>Bags &amp; Shoes</span></a></li>
        <li class="nav-kids"><a class="" data-spm-anchor-id="2114.11010108.19.9" data-widget-cid="widget-18"
                                href="#j-industry-floor-kids"><i></i><span>Kids &amp; Mother</span></a></li>
        <li class="nav-sports"><a class="" data-spm-anchor-id="2114.11010108.19.10" data-widget-cid="widget-18"
                                  href="#j-industry-floor-sports"><i></i><span>Sports &amp; Outdoors</span></a></li>
        <li class="nav-automobiles"><a class="" data-spm-anchor-id="2114.11010108.19.11" data-widget-cid="widget-18"
                                       href="#j-industry-floor-automobiles"><i></i><span>Automobiles &amp; Motorcycles</span></a>
        </li>
        <li class="nav-beauty"><a class="" data-spm-anchor-id="2114.11010108.19.12" data-widget-cid="widget-18"
                                  href="#j-industry-floor-beauty"><i></i><span>Beauty &amp; Health</span></a></li>
        <li class="nav-wedding"><a class="" data-spm-anchor-id="2114.11010108.19.13" data-widget-cid="widget-18"
                                   href="#j-industry-floor-wedding"><i></i><span>Wedding &amp; Events</span></a></li>
    </ul>
</div>