<!--Menu mobile-->
<header class="ms-header">
    <a href="<?php echo $this->url->get() ?>" id="ms-outer" class="for-outer" style="padding: 12px 0 9px 0;">
        <img src="//img.alicdn.com/tps/i4/TB1cCb4HpXXXXcZXVXXyo3wIXXX-220-54.png" alt="AE Logo"
             style="width:110px;height:27px;">
    </a>
    <div class="header-main">
        <span class="drawer btn-menu-mobile"></span>
        <a href="<?php echo $this->url->get() ?>" class="logo" id="ms-logo" data-stat="front_page::aecom::aecom_button"
           style="padding: 12px 0 9px 0;"><img src="img/TB1cCb4HpXXXXcZXVXXyo3wIXXX-220-54.png" alt="AE Logo"
                                               style="width:110px;height:27px;"></a>

        <div class="position-right">
            <span class="search" data-stat="all_page::m_search::search_button"></span>
            <a href="<?php echo $this->url->get("shoping-cart") ?>" id="ms-cart" class="cart"
               data-stat="all_page::shoppingcart::shoppingcart_button"><span class="inline-block">0</span></a>
        </div>
    </div>
</header>
<div class="ms-drawer-mask"><span class="ms-drawer-back"></span></div>
<section class="ms-drawer ">
    <div class="ms-drawer-loginInfo">

        <div class="drawer-unlogin">
            <a href="<?php echo $this->url->get("user") ?>" class="drawer-signin">Đăng Nhập</a>
            <a href="<?php echo $this->url->get("user/register") ?>" class="drawer-join">Đăng Ký</a>
        </div>
        <div class="drawer-logined">
            <div class="drawer-username"></div>
            <!-- <div class="drawer-email"></div> -->
        </div>
    </div>

    <ul class="drawer-guide">
        <!-- Home -->
        <li class="drawer-home"><a href="<?php echo $this->url->get() ?>" data-stat="menu_page::menu_home::home_button"><i
                    class="fa fa-home "></i><span>Home</span></a></li>

        <?php if ($manufacturer) {
            foreach ($manufacturer as $key => $manu) { ?>
                <li class="drawer-myOrder">
                    <a class="drawer-myOrder" href="<?php echo $this->url->get("manufacturer/").$manu->ma_id ?>" >
                        <span><?php echo $manu->ma_name ?></span>
                    </a>
                </li>
            <?php }
        } ?>
    </ul>

</section>
<!--End Mobile Mobile-->