<div class="wrapper main-nm-home-area"  >
    <?php
    if (count($featureBanner) > 0) {
        foreach ($featureBanner as $fea) {
            ?>
            <div class="nm-feature-area">
                <h4 class="nm-feature-title-mobile"><?php $fea->ba_name ?></h4>
                <a href="<?php echo $this->url->get() . $fea->ba_link; ?>">
                    <img src="<?php echo $fea->ba_image_link; ?>" alt="">
                </a>
            </div>
        <?php
        }
    }
    ?>
</div>