<div class="top-container-bg"></div>
<div id="page">
    <div id="content">
        <div class="J_Layout layout grid-m">
            <div class="col-main">
                <div class="main-wrap J_Region">
                    <div class="J_Module skin-default" data-name="mm-ae-sns" data-skin="default"
                         data-guid="14358182556530" id="guid-14358182556530" data-version="7" data-type="3">
                        <div class="module" data-spm="1998596070">
                            <div class="tb-module mm-ae-sns"
                                 data-qr-code="//is.alicdn.com/kf/HTB17jSFLVXXXXa5aXXX760XFXXXg.png"
                                 data-tips="AliExpress Collections on App" data-has-sns="true" data-vk="" data-fb="true"
                                 data-ok="" data-twitter="true" data-url="">
                            </div>
                        </div>
                    </div>
                    <div class="J_Module skin-default" data-name="mm-ae-channel-header" data-skin="default"
                         data-guid="14358182556662" id="guid-14358182556662" data-version="12" data-type="3">
                        <div class="module" data-spm="1998596072">
                            <style type="text/css">
                                .mm-ae-channel-header .channel-title {
                                    margin-right: px;
                                }

                                @media (max-width: 1190px) {
                                    .reponsive-bg {
                                        background: url('https://img.alicdn.com/tps/TB1Io6QKFXXXXcHXpXXXXXXXXXX-1170-80.jpg') no-repeat left top;
                                        height: 80px;
                                    }
                                }
                            </style>
                            <div class="tb-module mm-ae-channel-header"
                                 style="background:url('<?php echo $this->url->get("public/FrontendCore/img/TB1eVfvJpXXXXaLXpXXJV5F3VXX-1920-80.jpg") ?>') no-repeat center;">
                                <div class="container reponsive-bg">
                                    <h2 class="channel-title"><a href="http://collections.aliexpress.com">ALIEXPRESS
                                            COLLECTIONS</a></h2>
                                    <span class="channel-desctions hidden-md hidden-sm">Discover our daily product collections and get inspired!</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="J_Module skin-default mm-ae-collection-banner-slide"
                         id="guid-14358182556744">
                        <div class="module">
                            <div class="banner-box ">
                                <div id="banner-slider" class="ui-banner-slider">

                                    <div class="ui-banner-slider-wrap">
                                        <div class=" ui-banner-slider-container ">
                                            <ul class="slides">
                                                <?php if ($slider) {
                                                    foreach ($slider as $sli) { ?>
                                                        <li style="width: 1349px;">
                                                            <a href="<?php echo $sli->ba_link ?>"
                                                               style="background:url('<?php echo $sli->ba_image_link ?>') no-repeat center; height:360px; display:block;"></a>

                                                        </li>
                                                    <?php }
                                                } ?>
                                            </ul>
                                        </div>

                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="J_Module skin-default" id="guid-14358182556703">
                        <div class="module">
                            <link
                                href="http://style.aliunicorn.com/css/6v/??apollo/mod/button/button-ws.css,apollo/mod/textfield/textfield-ws.css,apollo/mod/pagination/pagination-ws.css?v=20150702"
                                rel="stylesheet" type="text/css" media="all">
                            <div class="tb-module mm-ae-collection">
                                <div class="container">
                                    <div class="collection-nav util-clearfix">
                                        <div class="nav-main" id="tag-list">

                                            <a class="nav-items <?php if(!isset($cateQuery)) echo " current " ?> "
                                               href="<?php echo $this->url->get() . "collection" ?>">All</a>
                                            <?php if ($category_data) {
                                                foreach ($category_data as $cate) {
                                                    ?>
                                                    <a class="nav-items <?php echo isset($cateQuery) && $cateQuery==$cate->col_id ? " current " : "" ?>"
                                                       href="<?php echo $this->url->get() . "collection?cate=" . $cate->col_id ?>"><?php echo $cate->col_name ?></a>
                                                <?php }
                                            } ?>
                                            <div class="clearfix"></div>
                                        </div>
                                    </div>
                                    <div class="collection-wrap">
                                        <ul class="collection-list util-clearfix" id="collection-list">
                                            <?php if ($collection->items) {
                                                foreach ($collection->items as $category) {
                                                    if (count($category->CollectionModel) > 0) { ?>
                                                        <li class="collection-items col-lg-20 col-md-20 col-sm-20">
                                                            <div class="collection-main">
                                                                <div class="img-box util-clearfix">
                                                                    <a class="collection-img"
                                                                       href="<?php echo $this->url->get("collection/show/").$category->col_seo_link ?>">
                                                                        <img
                                                                            src="<?php echo $category->CollectionModel[0]->ProductModel->showImage() ?>"><i></i>
                                                                    </a>


                                                                    <a href="<?php echo $this->url->get("collection/show/").$category->col_seo_link ?>"
                                                                       class="collection-msg uitl-clearfix">
                                                                        <div class="collectin-description">
                                                                            <?php echo $category->col_name ?>
                                                                        </div>
                                                                        <div class="collection-total">
                                                                            <b><?php echo count($category->CollectionModel) ?></b>Sản
                                                                            phẩm
                                                                        </div>
                                                                    </a>
                                                                </div>
                                                                <div class="pro-list util-clearfix">

                                                                    <a class="list-items-img col-lg-20 col-md-20 col-sm-20"
                                                                       href="<?php echo $this->url->get("collection/show/").$category->col_seo_link ?>">
                                                                        <span class="small-product-items">
                                                                            <img
                                                                                src="<?php echo isset($category->CollectionModel[1]) ? $category->CollectionModel[1]->ProductModel->showImage() : ''; ?>"
                                                                                width="100%"><i></i>
                                                                        </span>
                                                                    </a>

                                                                    <a class="list-items-img col-lg-20 col-md-20 col-sm-20"
                                                                       href="<?php echo $this->url->get("collection/show/").$category->col_seo_link ?>">
                                                                        <span class="small-product-items">
                                                                            <img
                                                                                src="<?php echo isset($category->CollectionModel[2]) ? $category->CollectionModel[2]->ProductModel->showImage() : ''; ?>"
                                                                                width="100%"><i></i>
                                                                        </span>
                                                                    </a>
                                                                    <a class="list-items-img col-lg-20 col-md-20 col-sm-20"
                                                                       href="<?php echo $this->url->get("collection/show/").$category->col_seo_link ?>">
                                                                        <span class="small-product-items">
                                                                            <img
                                                                                src="<?php echo isset($category->CollectionModel[3]) ? $category->CollectionModel[3]->ProductModel->showImage() : ''; ?>"
                                                                                width="100%"><i></i>
                                                                        </span>
                                                                    </a>

                                                                </div>
                                                            </div>
                                                        </li>
                                                        <?php
                                                    }
                                                }
                                            } ?>


                                        </ul>
                                        <div id="pagination"
                                             class="ui-pagination ui-pagination-front ui-pagination-body util-clearfix">
                                            <div data-widget-cid="widget-37"
                                                 class="ui-pagination ui-pagination-body util-clearfix">
                                                <div class="ui-pagination-navi util-left">


                                                    <a class="ui-pagination-prev "
                                                       href="<?php echo isset($cateQuery) ? $this->url->get() . "collection?page=" . $collection->before."&cate=".$cateQuery : $this->url->get() . "collection?page=" . $collection->before ?>"
                                                       data-role="prev">previous</a>

                                                    <?php for ($i = 1; $i <= $collection->total_pages; $i++) { ?>
                                                        <a class="<?php if ($collection->current == $i) {
                                                            echo " ui-pagination-active ";
                                                        } ?> "
                                                           href="<?php echo isset($cateQuery) ?  $this->url->get() . "collection?page=" . $i."&cate=".$cateQuery : $this->url->get() . "collection?page=" . $i ?>"><?php echo $i; ?></a>
                                                    <?php } ?>


                                                    <a class="ui-pagination-next" data-role="next"
                                                       href="<?php echo isset($cateQuery) ? $this->url->get() . "collection?page=" . $collection->next."&cate=".$cateQuery : $this->url->get() . "collection?page=" . $collection->next ?>">next</a>


                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>