<div  class="wrapper">
    <div class="main-loginregister-area">
        <form id="forgot-form" onsubmit="forgotPasswordUser(); return false; " class="login-register-form form-horizontal" >
            <p>Nhập Email để lấy lại mật khẩu: <input required email="true" name="us_email" type="text" class="input-contact-form" placeholder="Email*"></p>

            <button style="margin: 20px 0px;" onclick="forgotPasswordUser()" type="button" class="btn-login-register">Gửi</button>

            <input  style="visibility: hidden;position: absolute;" type="submit">
        </form>

        <div class="clearfix"></div>
    </div>
</div>