<?php if ($data) { ?>
    <div class="form-group">
        <label class="control-label col-sm-2">Color </label>
        <div class="col-sm-10">
            <select id="select-search-color" name="plo_id" class="select-search-color">
                <option value="-1">Chose</option>
                <?php
                if ($option) {
                    foreach ($option->ProductListOptionModel as $val) {
                        foreach ($data->ProductOptionDetailModel as $optl) {
                            if ($val->plo_id == $optl->plo_id) {
                                ?>
                                <option  value="<?php echo $val->plo_id ?>"><?php echo $val->plo_name ?></option>
                                <?php
                            }
                        }
                    }
                }
                ?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2">Product Status</label>
        <div class="col-sm-10">
            <div class="checkbox checkbox-switch">
                <label>
                    <input name="product_status"  type="checkbox" data-on-color="success" data-off-color="danger" data-on-text="Còn" data-off-text="Hết" class="switch" checked="true" >
                    Còn Hàng/Hết Hàng
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2">Image</label>
        <div class="col-sm-10">

            <form style="min-height: 200px" action="#" class="dropzone" id="dropzone_multiple"></form>
        </div>
    </div>
    <div class="form-group">
        <div class="row grid-image-gallery">

        </div>
    </div>
    <script type="text/javascript">
        var id_image = 0;
        var plo_id = -1;
        $(document).ready(function () {
            $('[data-popup="lightbox"]').fancybox({
                padding: 3
            });
            $('.select-search-color').select2();
            $(".switch").bootstrapSwitch();
            $("#select-search-color").change(function () {
                var id = $(this).val();
                plo_id = id;
                var product_id = <?php echo $data->pr_id ?>;
                if (id != '-1') {
                    $.ajax({
                        type: "POST",
                        url: queryUrl + "/detail-content",
                        data: {"color_id": id, "product_id": product_id},
                        success: function (result)
                        {
                            $(".gallery-image").remove();
                            var data = $.parseJSON(result);
                            if (data.product_status == 1) {
                                $('input[name="product_status"]').bootstrapSwitch('state', true);
                            } else {
                                $('input[name="product_status"]').bootstrapSwitch('state', false);
                            }
                            //                            $(".gallery-image").remove();
                            if (data.image.length != 0) {
                                $.each(data.image, function (key, val) {
                                    var html = '';
                                    html = '<div class="col-lg-3 col-sm-6 gallery-image gallery-image-' + val.pi_id + '">\n\
                                    <div class="thumbnail">\n\
                                        <div class="thumb">\n\
                                            <img src="' + rootUrl + val.pi_image_link + '" alt="">\n\
                                            <input type="hidden" name="pi_image_link" value="' + val.pi_image_link + '">\n\
                                            <div class="caption-overflow">\n\
                                                <span>\n\
                                                    <a href="' + rootUrl + val.pi_image_link + '" data-popup="lightbox" rel="gallery" class="btn border-white text-white btn-flat btn-icon btn-rounded"><i class="icon-zoomin3"></i></a>\n\
                                                    <a onclick="deleteImage(' + val.pi_id + ')" href="javascript:;" class="btn border-danger text-danger-600 btn-flat btn-icon btn-rounded btn-remove-attribute"><i class="icon-minus3"></i></a>\n\
                                                </span>\n\
                                            </div>\n\
                                        </div>\n\
                                    </div>\n\
                                </div>';
                                    $(".grid-image-gallery").append(html);
                                    id_image = val.pi_id;
                                });
                                $("[data-popup='lightbox']").fancybox({
                                    padding: 3
                                });
                            }
                            uploadImage();

                        }
                    });
                }

            });

        });
        function uploadImage() {
            var pr_id = $("#select-product").val();
            var plo_id = $("#select-search-color").val();
            var myDropzone = new Dropzone("#dropzone_multiple", {
                init: function () {
                    this.on("addedfile", function (file) {
                        // Create the remove button
                        var removeButton = Dropzone.createElement("<a onclick='deleteImage(" + id_image + ")' href='javascript:;' class='dz-remove' >Remove file</a>");


                        // Capture the Dropzone instance as closure.
                        var _this = this;

                        // Listen to the click event
                        removeButton.addEventListener("click", function (e) {
                            // Make sure the button click doesn't submit the form:
                            e.preventDefault();
                            e.stopPropagation();

                            // Remove the file preview.
                            _this.removeFile(file);
                            // If you want to the delete the file on the server as well,
                            // you can do the AJAX request here.
                        });

                        // Add the button to the file preview element.
                        file.previewElement.appendChild(removeButton);
                    });
                },
                url: queryUrl + "/upload-image?pr_id=" + $("#select-product").val() + "&plo_id=" + plo_id,
                filesizeBase: 1024,
    //                uploadMultiple: true,
    //                addRemoveLinks: true,
                dictRemoveFile: "Remove zxc",
                paramName: pr_id, // The name that will be used to transfer the file
                dictDefaultMessage: 'Drop files to upload <span>or CLICK</span>',
                maxFilesize: 0.5, // MB
                maxFiles: 20,
                acceptedFiles: "image/jpeg,image/png",
                accept: function (file, done) {
                    var html = '';
                    html = '<div style="height: 0px;visibility: hidden" class="col-lg-3 col-sm-6 gallery-image gallery-image-' + id_image + '">\n\
                                    <div class="thumbnail">\n\
                                        <div class="thumb">\n\
                                            <img src="' + rootUrl + 'public/uploads/images/upload/' + pr_id + '/' + file.name + '" alt="">\n\
                                            <input type="hidden" name="pi_image_link" value="public/uploads/images/upload/' + pr_id + '/' + file.name + '">\n\
                    <div class="caption-overflow">\n\
                    <span>\n\
                <a href="' + rootUrl + 'public/uploads/images/upload/' + pr_id + '/' + file.name + '" data-popup="lightbox" rel="gallery" class="btn border-white text-white btn-flat btn-icon btn-rounded"><i class="icon-zoomin3"></i></a>\n\
            <a onclick="deleteImage(' + id_image + ')" href="javascript:;" class="btn border-danger text-danger-600 btn-flat btn-icon btn-rounded btn-remove-attribute"><i class="icon-minus3"></i></a>\n\
        </span>\n\
            </div>\n\
        </div>\n\
                                    </div>\n\
                                </div>';
                    $(".grid-image-gallery").append(html);
                    $('[data-popup="lightbox"]').fancybox({
                        padding: 3
                    });
                    id_image++;
                    done();
                }
            });
            myDropzone.on("success", function (file, responseText) {
                var result = $.parseJSON(responseText);
                if (result.status == 0) {
                    WarningNotice('Lỗi', result.message);
                    myDropzone.removeFile(file);
                    $(".gallery-image").remove();
                }


            });
        }
        function deleteImage(id) {
            $(".gallery-image-" + id).remove();
        }
    </script>
<?php } ?>