<style>
    .index-page{
        background-color: #fff;
    }
</style>
<div class="container" >
    <div style="text-align: center;padding: 20px 0;" class="shopping-cart-area">
        <img class="icon-order-susess" src="<?php echo $this->config['rootUrl'] . "public/FrontendCore/img/"; ?>icon-big-order-susess.png" alt="">
        <h1 class="text-order-susess">Đơn hàng của bạn đã thanh toán thành công.</h1>
        <h1 class="text-order-susess">Xin Cảm Ơn</h1>
        <div class="order-susess-btn-area">
            <a style="display: inline-block" href="<?php echo $this->url->get('') ?>" class="btn-light btn-popup btn-cart">Trang Chủ</a>
            <a style="display: inline-block" href="<?php echo $this->url->get('today-sale') ?>" class="btn-dark btn-popup btn-continue">Sản phẩm khác</a>
    </div>
</div>
